definitions:
  tests: &test
    name: Tests
    image: adaptavist/terraform:alpine-0.12.8-dev
    script:
      - (echo ${PIPELINE_GIT_PRIVATE_KEY} | base64 -d >> ~/.ssh/id_rsa) && chmod 0600 ~/.ssh/id_rsa
      - terraform fmt -check -recursive -diff
      - (cd test && AWS_DEFAULT_REGION=us-east-1 AWS_ACCESS_KEY_ID="${TF_TEST_AWS_ACCESS_KEY_ID}" AWS_SECRET_ACCESS_KEY="${TF_TEST_AWS_SECRET_ACCESS_KEY}" go test)

  release: &release
    name: Release
    image: adaptavist/all-tools:latest
    caches:
      - node
    script:
      - npm install --save-dev
      - npx semantic-release -r ${BITBUCKET_GIT_HTTP_ORIGIN}

pipelines:
  default:
    - step: *test
  branches:
    master:
      - step: *release
